{
  "invalid": [
    {
      "name": "data has not taskId",
      "cases": [
        [],
        null,
        {},
        "",
        0,
        "0",
        true,
        {
          "key1": "val1"
        }
      ],
      "excepted": {
        "code": "invalid-argument",
        "message": "Bad Request",
        "details": "Some went wrong ðŸ¤« Try again ðŸ™‚"
      }
    },
    {
      "name": "data.taskId is not string",
      "cases": [
        {
          "taskId": []
        },
        {
          "taskId": null
        },
        {
          "taskId": {}
        },
        {
          "taskId": 0
        },
        {
          "taskId": true
        }
      ],
      "excepted": {
        "code": "invalid-argument",
        "message": "Bad Request",
        "details": "Some went wrong ðŸ¤« Try again ðŸ™‚"
      }
    },
    {
      "name": "interrupt if user has not this task",
      "cases": [
        {
          "taskId": "task"
        }
      ],
      "excepted": {
        "code": "invalid-argument",
        "message": "Bad Request",
        "details": "Some went wrong ðŸ¤« Try again ðŸ™‚"
      }
    }
  ]
}
